# Generated by Django 3.0.7 on 2020-07-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clgdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('enrollnment', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=30)),
                ('subject2', models.CharField(max_length=30)),
                ('subject3', models.CharField(max_length=30)),
                ('subject4', models.CharField(max_length=30)),
                ('subject5', models.CharField(max_length=30)),
                ('subject6', models.CharField(max_length=30)),
                ('subject7', models.CharField(max_length=30)),
                ('subject8', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('clgdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndGemapp.clgdata')),
                ('subdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndGemapp.subdata')),
            ],
        ),
    ]
