# Generated by Django 3.0.7 on 2020-07-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0002_auto_20200709_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='clgdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=30)),
                ('year', models.CharField(blank=True, max_length=30)),
                ('enrollnment', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(blank=True, max_length=30)),
                ('subject2', models.CharField(blank=True, max_length=30)),
                ('subject3', models.CharField(blank=True, max_length=30)),
                ('subject4', models.CharField(blank=True, max_length=30)),
                ('subject5', models.CharField(blank=True, max_length=30)),
                ('subject6', models.CharField(blank=True, max_length=30)),
                ('subject7', models.CharField(blank=True, max_length=30)),
                ('subject8', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='enrollnment',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject6',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject7',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subject8',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='year',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='clgdata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EndGemapp.clgdata'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subdata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EndGemapp.subdata'),
        ),
    ]
