# Generated by Django 3.0.7 on 2020-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0003_auto_20200710_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='clgdata',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subdata',
        ),
        migrations.AddField(
            model_name='userdata',
            name='branch',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='enrollnment',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject6',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject7',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject8',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='year',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='clgdata',
        ),
        migrations.DeleteModel(
            name='subdata',
        ),
    ]
