# Generated by Django 3.0.7 on 2020-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0004_auto_20200710_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_to_upload', models.FileField(upload_to='media/subject1/')),
            ],
        ),
    ]
