# Generated by Django 3.0.7 on 2020-07-17 16:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0006_auto_20200717_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfolder',
            name='File_to_upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/subject1/'), upload_to=''),
        ),
    ]
