# Generated by Django 3.0.7 on 2020-07-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0007_auto_20200717_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadfolder',
        ),
    ]
