# Generated by Django 3.0.7 on 2020-07-18 07:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0008_delete_uploadfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_to_upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/subject1/'), upload_to='')),
            ],
        ),
    ]
