# Generated by Django 3.0.7 on 2020-07-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0009_uploadfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadfolder',
        ),
    ]
