# Generated by Django 3.0.7 on 2020-07-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndGemapp', '0010_delete_uploadfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
